# Generated by Django 4.2.4 on 2023-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Alarme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
    ]
