# Generated by Django 4.2.4 on 2023-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_alarme',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
