# Generated by Django 4.2.4 on 2023-10-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0002_alter_client_alarme_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch_Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicule', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
