# Generated by Django 4.2.4 on 2023-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0004_aide_engin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aide_engin',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='user_directory_path'),
        ),
    ]
