# Generated by Django 4.2.4 on 2023-12-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0005_aide_engin_fichier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aide_Engin',
        ),
    ]
